export class ElementorAdapter {
  constructor(axiosInstance) {
    this.axios = axiosInstance;
  }

  encode4ByteCharsToEntities(str) {
    if (!str) return str;
    return str.replace(/[\uD800-\uDBFF][\uDC00-\uDFFF]/g, (match) => {
      const high = match.charCodeAt(0);
      const low = match.charCodeAt(1);
      const codePoint = ((high - 0xD800) * 0x400) + (low - 0xDC00) + 0x10000;
      return `&#${codePoint};`;
    });
  }

  async deploy(params) {
    const {
      payload,
      targetObj,
      actionType,
      endpoint, // The standard WP endpoint, not the elementor one
      method
    } = params;

    let proposedText = payload.html || payload.proposedChange || payload.content || '';
    proposedText = this.encode4ByteCharsToEntities(proposedText);

    const isMetadata = payload.changeType === 'metadata';
    const requestData = { status: payload.isDraft ? 'draft' : 'publish' };

    let elementorUpdated = false;

    if (isMetadata) {
      const isTitle = (
        (payload.description && payload.description.toLowerCase().includes('title')) ||
        (payload.title && payload.title.toLowerCase().includes('title')) ||
        (payload.currentState && payload.currentState.toLowerCase().includes('title'))
      );
      if (isTitle) {
        requestData.title = proposedText;
      } else {
        requestData.excerpt = proposedText;
      }

      // Metadata changes are pushed directly via native WordPress API
      const deployRes = await this.axios({
        method,
        url: endpoint,
        data: requestData
      });
      return {
        updatedObject: deployRes.data,
        method: 'native_wordpress' // Metadata is always native
      };
    } else {
      // Standard Content Change using the custom Elementor plugin endpoint
      let search = payload.currentState || '';
      
      // Fix broken HTML tags generated by AI or bad UI copy/paste
      search = search.replace(/^([a-z1-6]+>)/i, '<$1');
      search = search.replace(/(<\/[a-z1-6]+)$/i, '$1>');
      if (!search) {
        console.warn(`[ElementorAdapter] No search text provided for Elementor update. Falling back to native WordPress content append.`);
        requestData.content = (targetObj.content?.raw || '') + `\n<!-- wp:html -->\n${proposedText}\n<!-- /wp:html -->`;
        const deployRes = await this.axios({ method, url: endpoint, data: requestData });
        return { updatedObject: deployRes.data, method: 'native_wordpress_fallback' };
      }

      let finalReplaceText = proposedText;
      if (actionType === 'insert_after') {
        finalReplaceText = search + "\n" + proposedText;
      } else if (actionType === 'insert_before') {
        finalReplaceText = proposedText + "\n" + search;
      }

      try {
        // Build the URL to the custom elementor plugin
        const baseUrl = endpoint.split('/wp-json/wp/v2/')[0] || endpoint.split('/?rest_route=/wp/v2/')[0];
        const restPrefix = endpoint.includes('/wp-json') ? '/wp-json' : '/?rest_route=';
        const elementorEndpoint = baseUrl + (restPrefix === '/wp-json' ? `/wp-json/clicktrends/v1/update-elementor/${targetObj.id}` : `/?rest_route=/clicktrends/v1/update-elementor/${targetObj.id}`);

        console.log(`[ElementorAdapter] Sending to Elementor Plugin -> Search: "${search}", Replace: "${finalReplaceText}"`);
        const elemRes = await this.axios.post(elementorEndpoint, {
          search_text: search,
          replace_text: finalReplaceText
        });
        
        if (elemRes.data && elemRes.data.success) {
          elementorUpdated = true;
          console.log(`[ElementorAdapter] Elementor updated successfully: ${elemRes.data.message}`);
        } else {
          throw new Error("Plugin responded with success: false");
        }
      } catch (elemErr) {
        console.warn(`[ElementorAdapter] Elementor plugin update failed: ${elemErr.response?.data?.message || elemErr.message}. Falling back to native WP.`);
        requestData.content = (targetObj.content?.raw || '') + `\n<!-- wp:html -->\n${proposedText}\n<!-- /wp:html -->`;
        const deployRes = await this.axios({ method, url: endpoint, data: requestData });
        return { updatedObject: deployRes.data, method: 'native_wordpress_fallback' };
      }

      // If the elementor plugin succeeded, we still need to return the updated object metadata.
      // So we fetch it via a GET to the standard endpoint
      const updatedObjRes = await this.axios.get(endpoint);

      return {
        updatedObject: updatedObjRes.data,
        method: elementorUpdated ? 'elementor_plugin' : 'native_wordpress_fallback'
      };
    }
  }
}
